import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#424751",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        outline: "#737782",
        "outline-variant": "#c2c6d2",
        "surface-tint": "#2a5ea5",
        primary: "#003063",
        "on-primary": "#ffffff",
        "primary-container": "#00468c",
        "on-primary-container": "#8cb6ff",
        "inverse-primary": "#a9c7ff",
        secondary: "#5d5f5f",
        "on-secondary": "#ffffff",
        "secondary-container": "#dfe0e0",
        "on-secondary-container": "#616363",
        tertiary: "#680007",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#93000e",
        "on-tertiary-container": "#ff9990",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#a9c7ff",
        "on-primary-fixed": "#001b3d",
        "on-primary-fixed-variant": "#00468c",
        "secondary-fixed": "#e2e2e2",
        "secondary-fixed-dim": "#c6c6c7",
        "on-secondary-fixed": "#1a1c1c",
        "on-secondary-fixed-variant": "#454747",
        "tertiary-fixed": "#ffdad6",
        "tertiary-fixed-dim": "#ffb4ac",
        "on-tertiary-fixed": "#410003",
        "on-tertiary-fixed-variant": "#93000e",
        background: "#fcf9f8",
        "on-background": "#1c1b1b",
        "surface-variant": "#e5e2e1",
      },
      fontFamily: {
        lexend: ["Lexend", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-2xl": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-xl": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "stat-lg": ["40px", { lineHeight: "1", fontWeight: "800" }],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        "element-gap": "16px",
        gutter: "24px",
        "margin-mobile": "16px",
        "section-gap": "80px",
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
